version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./docker_compose.env
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  web:
    build: .
    command: sh -c "/wait && python manage.py migrate"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      WAIT_HOSTS: db:5432, redis:6379

