version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./docker_compose.env
    ports:
      - "5432:5432"
    networks:
      service1_net:
        ipv4_address: 172.22.0.101

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      service1_net:
        ipv4_address: 172.22.0.100


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      service1_net:
    depends_on:
      - db
      - redis

networks:
  service1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16