version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./docker_compose.env
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  web:
    env_file:
      - ./helpdesk_web.env
    build: .
    command: sh -c "/wait && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mysql
      - redis
    environment:
      WAIT_HOSTS: db:5432, redis:6379, mysql:3306
      WAIT_HOSTS_TIMEOUT: 200

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgresql
    ports:
        - "5050:80"