# Generated by Django 3.1.7 on 2021-03-08 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Se permiten entre 9 y 15 números', regex='^\\d{9,15}$')]),
        ),
    ]
