# Generated by Django 2.2.17 on 2020-11-08 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=72)),
                ('message', models.CharField(max_length=1000)),
                ('question_datetime', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Ingresá tu mail de uso frecuente', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Se permiten entre 9 y 15 números', regex='^\\d{9,15}$')])),
            ],
        ),
    ]
