# Generated by Django 2.2.16 on 2020-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
