# Generated by Django 2.2.16 on 2020-10-23 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0003_auto_20201014_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default=None, help_text='Ingresá tu mail de uso frecuente', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Se permiten entre 9 y 15 números', regex='^\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='question',
            name='urgency',
            field=models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
